### ISSUE TITLE
Basic Defences

### ISSUE THREAD

**Issue by curiousinternals** [bug-quota/slime.factorio#7]
Need blueprints for turret blocks, walls and any internal ammo logistics systems. Ideally turrets should be loaded from buffer chests: Yellow belts might not keep up with higher level enemies.

Bonus points if the buffer chests can somehow automatically empty to share ammo with nearby turrets. Super cookie points if the ammo type can be mostly automatically replaced if we get reliable uranium ammo some day. I don't think this is really possible in a sane way though. I wouldn't recommend wasting your life on it.

**Comment by NatPro38** [comment]
- [x] Turret Straight section
- [x] Turret Outer Corner
- [x] Turrets Feed From Buffers-> Set Ammo to Load with Green Wire
- [x] Buffers Share With Other Buffers
- [x] Buffers can unload Useless Ammo -> Set Unload Filters With Red Wire
- [x] Ammo Belt Feed
- [x] Ammo Belt Recycling

No Inside Corner Sections as it Does Not reduce perimeter size and only Increases the number of weaker Outer Corner Sections.
